### ISSUE TITLE
Capacitors not connected to Vcc

### ISSUE THREAD

**Issue by alevy** [helena-project/imix#7]
The SAM4L pins 8 and 97 are not connected to VCC_MCU_3V3. They are instead connected to the decoupling capacitors C19 and C22 without being connected directly to the power net. 

This results in a variety of strange behaviors. Essentially, certain peripheral banks in the MCU try to draw power from VDDIO, but instead they are drawing from the charge coincidentally stored in C19 and C22. When C19 and C22 are drained, things stop working.

This error happened because of a nuance with EAGLE. EAGLE should have caught this as a Design Rule error, but due to the specific way the footprint was made, it incorrectly assumed that all of the VDDIO pins were internally connected. Thus, once any of the VDDIO pins (8, 97, 87, or 88) were connected to power, it assumed all four were connected to power, and didn't generate the necessary airwires to connect each pin to power individually.

**Comment by shaneleonard** [comment]
The commit 99e1496 fixes this issue, however it does not fix EAGLE's misinterpretation of the footprint. Need an additional commit to address that.
