### ISSUE TITLE
RF233 weak radio reception

### ISSUE THREAD

**Issue by alevy** [helena-project/imix#9]
There is evidence that the radio signal for the RF233 is pretty weak. This might be due to interference from the RNG's ground plane.

**Comment by shaneleonard** [comment]
Commit 99e1496 should be sufficient to fix this, but we are awaiting additional testing to confirm that this is the correct solution.

**Comment by shaneleonard** [comment]
Tests are inconclusive as to how bad this issue is, but the weaker signal strength is still sufficient for development work.  Closing for now, may reopen if problem persists on next revision but it should be fixed.
